#!/usr/bin/env bash
# How to install nginx on a remote server and configure it
sudo apt update 
sudo apt install nginx -y
echo "Holberton School" | sudo tee /var/www/html/index.html >/dev/null 
sudo service nginx restart
sudo ufw allow 'Nginx HTTP'
